version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      electron:
        patterns: ["electron", "electron-builder"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
